# Generated by Django 5.1.6 on 2025-04-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_account_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='default_avatar.png', upload_to='profile_pics/'),
        ),
    ]
